spring.application.name=backend


spring.datasource.url=${jdbc:mysql://your-cloud-db-host:3306/healgo}
spring.datasource.username=${root}
spring.datasource.password=${8888}
# This tells Hibernate exactly what to expect if it can't auto-detect it
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}
